### ISSUE TITLE
[Bug] crashed dedicated server with class not found

### ISSUE THREAD

**Issue by kreezxil** [Injourn/UpgradedWolves#1]
**Describe the bug**
Crashes dedicated server with class not found

**To Reproduce**
Create a server pack with the mod in it, boot and watch it crash

**Expected behavior**
to not crash

**Screenshots**
n/a

**Version [e.g. 0.3]
1.16.5-0.4.1

**Additional context**

server crash report/log: https://gist.github.com/a312f5483320a72c90055e408b8c8048

**Comment by Injourn** [comment]
Fixed in the newest version, hopefully...
